<?php
/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/functions.php' );
require ( get_template_directory() . '/includes/hooks.php' );
require ( get_template_directory() . '/includes/strap-extras.php' );
require ( get_template_directory() . '/includes/cpt.php' );

/**
 * Slightly Modified Options Framework
 */
require_once ('admin/index.php');

if ( ! function_exists('bi_get_data') ) {
	function bi_get_data($id, $fallback = false) {
		global $smof_data;
		if ( $fallback == false ) $fallback = '';
		$output = ( isset($smof_data[$id]) && $smof_data[$id] !== '' ) ? $smof_data[$id] : $fallback;
		return $output;
	}
}

add_theme_support( 'custom-background');

require_once( get_template_directory() .'/functions/social-icons.php' );
require_once( get_template_directory() .'/functions/custom-css.php' );
require_once( get_template_directory() .'/functions/login-logo.php' );
require_once( get_template_directory() .'/functions/google-fonts.php' );
require_once( get_template_directory() .'/functions/tracking.php' );